name: rnamaps
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.7.7  
  - pandas=0.24.2  
  - numpy=1.19.2  
  - pybedtools=0.8.1  
  - matplotlib=3.3.2
  - seaborn=0.11.0
  - scipy=1.3.1